-- create schema
CREATE SCHEMA IF NOT EXISTS alt_school;

-- create table
CREATE TABLE IF NOT EXISTS alt_school.dataco_supply_chain (
    "type" VARCHAR(50),
    days_for_shipping INTEGER,
    days_for_shipment_scheduled INTEGER,
    benefit_per_order NUMERIC,
    sales_per_customer NUMERIC,
    delivery_status VARCHAR(50),
    late_delivery_risk INTEGER,
    category_id INTEGER,
    category_name VARCHAR(100),
    customer_city VARCHAR(100),
    customer_country VARCHAR(100),
    customer_email VARCHAR(50),
    customer_fname VARCHAR(100),
    customer_id INTEGER,
    customer_lname VARCHAR(100),
    customer_password VARCHAR(50),
    customer_segment VARCHAR(50),
    customer_state VARCHAR(50),
    customer_street VARCHAR(100),
    customer_zipcode INTEGER,
    department_id INTEGER,
    department_name VARCHAR(100),
    latitude NUMERIC,
    longitude NUMERIC,
    market VARCHAR(50),
    order_city VARCHAR(100),
    order_country VARCHAR(100),
    order_customer_id INTEGER,
    order_date TIMESTAMP,
    order_id INTEGER,
    order_item_cardprod_id INTEGER,
    order_item_discount NUMERIC,
    order_item_discount_rate NUMERIC,
    order_item_id INTEGER,
    order_item_product_price NUMERIC,
    order_item_profit_ratio NUMERIC,
    order_item_quantity INTEGER,
    sales NUMERIC,
    order_item_total NUMERIC,
    order_profit_per_order NUMERIC,
    order_region VARCHAR(100),
    order_state VARCHAR(100),
    order_status VARCHAR(50),
    order_zipcode INTEGER,
    product_card_id INTEGER,
    product_category_id INTEGER,
    product_description TEXT,
    product_image TEXT,
    product_name VARCHAR(255),
    product_price NUMERIC,
    product_status VARCHAR(50),
    shipping_date TIMESTAMP,
    shipping_mode VARCHAR(100)
);


-- populate table
COPY alt_school.dataco_supply_chain (
    "type",
    days_for_shipping,
    days_for_shipment_scheduled,
    benefit_per_order,
    sales_per_customer,
    delivery_status,
    late_delivery_risk,
    category_id,
    category_name,
    customer_city,
    customer_country,
    customer_email,
    customer_fname,
    customer_id,
    customer_lname,
    customer_password,
    customer_segment,
    customer_state,
    customer_street,
    customer_zipcode,
    department_id,
    department_name,
    latitude,
    longitude,
    market,
    order_city,
    order_country,
    order_customer_id,
    order_date,
    order_id,
    order_item_cardprod_id,
    order_item_discount,
    order_item_discount_rate,
    order_item_id,
    order_item_product_price,
    order_item_profit_ratio,
    order_item_quantity,
    sales,
    order_item_total,
    order_profit_per_order,
    order_region,
    order_state,
    order_status,
    order_zipcode,
    product_card_id,
    product_category_id,
    product_description,
    product_image,
    product_name,
    product_price,
    product_status,
    shipping_date,
    shipping_mode
) 
FROM '/data/dataco_supply_chain.csv' DELIMITER ',' CSV HEADER;
